#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model ScalableTranslationStatistics.Fluid.Examples.ScalableHydraulics
 Dymola Version 2024x Refresh 1, 2024-04-12 translated this at Fri May 17 12:23:07 2024

  OutputCPUtime = true;
 */

#include "matrixop.h"
#include "matrixop.c"
#if defined(DynSimStruct)
static double DymArrays0[6]={2.0, 5.0, 3.0, 4.0, 2.0, 4.0};
#endif
/* Declaration of C-structs */
/* Prototypes for functions used in model */
DYMOLA_STATIC double   nLSystem_numericx_0pump_CalcDensityx_0Unique2(double  
  p0_0);
/* Codes used in model */

/* Flattened Modelica model:

function nLSystem.numeric_pump.CalcDensity_Unique2
discrete input Real p "pressure";
discrete output Real density "density";
protected 
parameter Real M(start = 0.028964) "molar mass (dry air)";
parameter Real R(start = 8.314) "universal gas constant";
parameter Real T(start = 298.15) "fixed temperature ";
public 
algorithm 
density := 1;
assert(density > 0, "neg. density");
end nLSystem.numeric_pump.CalcDensity_Unique2;

  */
DYMOLA_STATIC double   nLSystem_numericx_0pump_CalcDensityx_0Unique2(double  
  p0_0) {
  PushContext("nLSystem.numeric_pump.CalcDensity_Unique2")
  {
    /* Declare outputs and temporaries */
    double   density0_0;
    double   M0_0;
    double   R0_0;
    double   T0_0;
    density0_0=0;
    M0_0 = 0.028964;
    R0_0 = 8.314;
    T0_0 = 298.15;
    /* Start of real code */
      density0_0 = 1;
      AssertModelica(density0_0 > 0,"density > 0", "neg. density");
    /* Output section */
    PopContext()
    return density0_0;
  }}
/* DSblock C-code: */

#define NX_    3
#define NX2_   14
#define NU_    0
#define NY_    2
#define NW_    94
#define NWP_   23
#define NP_    53
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -481624216
#define NHash2_ 630697747
#define NHash3_ 58841257
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    112
#define SizePre_ 0
#define SizeEq_ 17
#define SizeDelay_ 0
#define QNLmax_ 4
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 412
#define NGlobalHelpI_ 102
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include "moutil.c"
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="ScalableTranslationStatistics.Fluid.Examples.ScalableHydraulics";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "C:/Users/MatthiasSchaefer/AppData/Roaming/DassaultSystemes/Dymola/dymola.lic";
#include "dsblock1.c"

/* Define variable names. */

#define Sections_

TranslatedEquations
DYNX(Y_,0) = CurrentClockTime;
if (DYNEvent) DYNX(Y_,1) += 1;
InitialSection
#if defined(DynSimStruct)
DYNX(W_,27) = 0.01;
DYNX(W_,29) = 0.01;
DYNX(W_,31) = 0.01;
DYNX(W_,33) = 0.01;
DYNX(W_,49) = 0.01;
DYNX(W_,51) = 0.01;
DYNX(W_,60) = 0.01;
DYNX(W_,62) = 0.01;
DYNX(W_,64) = 0.01;
DYNX(W_,66) = 0.01;
DYNX(W_,68) = 0.01;
DYNX(W_,73) = 0.01;
DYNX(W_,75) = 0.01;
DYNX(W_,77) = 0.01;
#endif

InitialSection
#if defined(DynSimStruct)
memcpy(&DYNX(W_,0), &DymArrays0, sizeof(double)*6);
DYNX(W_,9) = 4;
DYNX(W_,10) = 2;
DYNX(W_,14) = 2;
DYNX(W_,15) = true;
DYNX(W_,16) = 2;
DYNX(W_,17) = 5;
DYNX(W_,18) = true;
DYNX(W_,19) = 5;
DYNX(W_,20) = 3;
DYNX(W_,21) = false;
DYNX(W_,22) = 3;
DYNX(W_,11) = true;
DYNX(W_,12) = true;
DYNX(W_,13) = false;
DYNX(W_,8) = true;
DYNX(W_,7) = 100;
DYNX(W_,6) = 100;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,41) = DYNX(DP_,13);
DYNX(W_,52) = DYNX(DP_,24);
DYNX(W_,69) = DYNX(DP_,41);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,52) = DYNX(DP_,24);
 /* Linear system of equations to solve. */
DYNX(X_,1) = 0.0;
SolveScalarLinearParametric( -divGuarded(8.31446261815324*DYNX(DP_,25),
  "8.31446261815324*nLSystem[2].volume.T",DYNX(DP_,26),"nLSystem[2].volume.M"),
  " -8.31446261815324*nLSystem[2].volume.T/nLSystem[2].volume.M",  -DYNX(W_,52)*
  DYNX(DP_,23)," -nLSystem[2].volume.p*nLSystem[2].volume.V", DYNX(X_,1),
  "nLSystem[2].volume.m");
 /* End of Equation Block */ 

DYNX(W_,41) = DYNX(DP_,13);
 /* Linear system of equations to solve. */
DYNX(X_,0) = 0.0;
SolveScalarLinearParametric( -divGuarded(8.31446261815324*DYNX(DP_,14),
  "8.31446261815324*nLSystem[1].volume.T",DYNX(DP_,15),"nLSystem[1].volume.M"),
  " -8.31446261815324*nLSystem[1].volume.T/nLSystem[1].volume.M",  -DYNX(W_,41)*
  DYNX(DP_,12)," -nLSystem[1].volume.p*nLSystem[1].volume.V", DYNX(X_,0),
  "nLSystem[1].volume.m");
 /* End of Equation Block */ 

DYNX(W_,69) = DYNX(DP_,41);
 /* Linear system of equations to solve. */
DYNX(X_,2) = 0.0;
SolveScalarLinearParametric( -divGuarded(8.31446261815324*DYNX(DP_,42),
  "8.31446261815324*nLSystem[3].volume.T",DYNX(DP_,43),"nLSystem[3].volume.M"),
  " -8.31446261815324*nLSystem[3].volume.T/nLSystem[3].volume.M",  -DYNX(W_,69)*
  DYNX(DP_,40)," -nLSystem[3].volume.p*nLSystem[3].volume.V", DYNX(X_,2),
  "nLSystem[3].volume.m");
 /* End of Equation Block */ 

InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
if (NewParameters_) {
DYNX(DYNhelp,0) = divinvGuarded(DYNX(DP_,15),"nLSystem[1].volume.M");
}
DYNX(W_,41) = RememberSimple_(DYNX(W_,41), 0);
SolveScalarLinearParametric(DYNX(DP_,12),"nLSystem[1].volume.V", DYNX(DYNhelp,0)
  *DYNX(X_,0)*8.31446261815324*DYNX(DP_,14),"nLSystem[1].volume.m*8.31446261815324*nLSystem[1].volume.T/nLSystem[1].volume.M",
   DYNX(W_,41),"nLSystem[1].volume.p");
 /* End of Equation Block */ 

DYNX(W_,23) = IF LessTime(0.5, 0) THEN 50 ELSE 100;
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
if (NewParameters_) {
DYNX(DYNhelp,1) = divinvGuarded(DYNX(DP_,26),"nLSystem[2].volume.M");
}
DYNX(W_,52) = RememberSimple_(DYNX(W_,52), 1);
SolveScalarLinearParametric(DYNX(DP_,23),"nLSystem[2].volume.V", DYNX(DYNhelp,1)
  *DYNX(X_,1)*8.31446261815324*DYNX(DP_,25),"nLSystem[2].volume.m*8.31446261815324*nLSystem[2].volume.T/nLSystem[2].volume.M",
   DYNX(W_,52),"nLSystem[2].volume.p");
 /* End of Equation Block */ 


/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,2) = (PushModelContext(1,"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[1].numeric_pump.fluidPortIn.p)")
  nLSystem_numericx_0pump_CalcDensityx_0Unique2(DYNX(W_,41)));
PopModelContext();
DYNX(DYNhelp,3) = divinvGuarded(DYNX(DYNhelp,2),"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[1].numeric_pump.fluidPortIn.p)");
DYNX(W_,45) = DYNX(DYNhelp,3)*DYNX(DP_,17);

{ /* Non-linear system of equations to solve. */
/* Tag: simulation.nonlinear[1] */
/* Introducing 15 common subexpressions and reusing 1 variables totally whereof 16
   are global used in 5 expressions */
/* Of the common subexpressions 16 are reals, 0 are integers, and 0
   are booleans. */
const char*const varnames_[]={"nLSystem[2].parallelResistors.pressureLossTube[5].mdot",
   "nLSystem[2].parallelResistors.pressureLossTube[4].mdot", "nLSystem[2].parallelResistors.pressureLossTube[3].mdot",
   "nLSystem[2].parallelResistors.pressureLossTube[2].mdot", "nLSystem[1].numeric_pump.vdot"};
const double nominal_[]={100.0, 100.0, 100.0, 100.0, 1.0};
static const int sJacobianCG_[1] = {-1};
static const struct QJacobianTag_ sJacobianGC2_[1] = {{-1,0}};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 5, 0, 1, 1, 2, 4, 
  DYNX(DYNhelp,4), 123, DYNX(did_->helpvari_vec,0), 27);
NonLinearSystemSave(DYNX(W_,45), 0);
NonLinearSystemSave(DYNX(W_,23), 1);
NonLinearSystemSave(DYNX(W_,41), 2);
NonLinearSystemSave(DYNX(W_,52), 3);
SetInitVectorNH(x__, 1, DYNX(W_,68), Remember_(DYNX(W_,68), 2));
SetInitVectorNH(x__, 2, DYNX(W_,66), Remember_(DYNX(W_,66), 3));
SetInitVectorNH(x__, 3, DYNX(W_,64), Remember_(DYNX(W_,64), 4));
SetInitVectorNH(x__, 4, DYNX(W_,62), Remember_(DYNX(W_,62), 5));
SetInitVectorNH(x__, 5, DYNX(W_,44), Remember_(DYNX(W_,44), 6));
Residues;
  if (NewParameters_) {
  DYNX(DYNhelp,127) = divinvGuarded(DYNX(DP_,18),"nLSystem[1].numeric_pump.n_nom");
  }
  DYNX(DYNhelp,128) = DYNX(W_,44)*DYNX(DP_,18);
  DYNX(DYNhelp,129) = DYNX(W_,45)*DYNX(W_,23);
  DYNX(DYNhelp,130) = divGuarded(DYNX(DYNhelp,128),"nLSystem[1].numeric_pump.vdot*nLSystem[1].numeric_pump.n_nom",
    DYNX(DYNhelp,129),"nLSystem[1].numeric_pump.vdot_nom*nLSystem[1].numeric_pump.n");
  DYNX(W_,43) = sqr(DYNX(DYNhelp,127)*DYNX(W_,23))*(1-sqr(DYNX(DYNhelp,130)))*
    DYNX(DP_,16);
  DYNX(W_,46) = DYNX(W_,41)+DYNX(W_,43);
  DYNX(W_,67) = DYNX(W_,46)-DYNX(W_,52);
  DYNX(W_,65) = DYNX(W_,67);
  DYNX(W_,63) = DYNX(W_,67);
  DYNX(W_,61) = DYNX(W_,67);
  DYNX(DYNhelp,131) = (PushModelContext(1,"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[1].numeric_pump.fluidPortOut.p)")
    nLSystem_numericx_0pump_CalcDensityx_0Unique2(DYNX(W_,46)));
  PopModelContext();
  DYNX(W_,47) =  -DYNX(W_,44)*DYNX(DYNhelp,131);
  DYNX(W_,59) = DYNX(W_,67);
  DYNX(W_,60) =  -(DYNX(W_,47)+DYNX(W_,62)+DYNX(W_,64)+DYNX(W_,66)+DYNX(W_,68));
if (NewParameters_) {
DYNX(DYNhelp,132) = divinvGuarded(DYNX(DP_,30),"nLSystem[2].parallelResistors.pressureLossTube[1].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,133) = divinvGuarded(DYNX(DP_,31),"nLSystem[2].parallelResistors.pressureLossTube[1].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,134) = divinvGuarded(DYNX(DP_,32),"nLSystem[2].parallelResistors.pressureLossTube[2].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,135) = divinvGuarded(DYNX(DP_,33),"nLSystem[2].parallelResistors.pressureLossTube[2].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,136) = divinvGuarded(DYNX(DP_,34),"nLSystem[2].parallelResistors.pressureLossTube[3].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,137) = divinvGuarded(DYNX(DP_,35),"nLSystem[2].parallelResistors.pressureLossTube[3].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,138) = divinvGuarded(DYNX(DP_,36),"nLSystem[2].parallelResistors.pressureLossTube[4].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,139) = divinvGuarded(DYNX(DP_,37),"nLSystem[2].parallelResistors.pressureLossTube[4].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,140) = divinvGuarded(DYNX(DP_,38),"nLSystem[2].parallelResistors.pressureLossTube[5].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,141) = divinvGuarded(DYNX(DP_,39),"nLSystem[2].parallelResistors.pressureLossTube[5].mdot_nom");
}
SetVector(residue__, 1, DYNX(DYNhelp,132)*DYNX(W_,59)-powUnguarded(
  DYNX(DYNhelp,133)*DYNX(W_,60), 3));
SetVector(residue__, 2, DYNX(DYNhelp,134)*DYNX(W_,61)-powUnguarded(
  DYNX(DYNhelp,135)*DYNX(W_,62), 3));
SetVector(residue__, 3, DYNX(DYNhelp,136)*DYNX(W_,63)-powUnguarded(
  DYNX(DYNhelp,137)*DYNX(W_,64), 3));
SetVector(residue__, 4, DYNX(DYNhelp,138)*DYNX(W_,65)-powUnguarded(
  DYNX(DYNhelp,139)*DYNX(W_,66), 3));
SetVector(residue__, 5, DYNX(DYNhelp,140)*DYNX(W_,67)-powUnguarded(
  DYNX(DYNhelp,141)*DYNX(W_,68), 3));

{ /* No analytic Jacobian available*/
SolveNonLinearSystemOfEquationsNH(Jacobian__, 0, 0, 0, residue__, x__, 1, 
  "Tag: simulation.nonlinear[1]");
DYNX(W_,68) = GetVector(x__, 1);
DYNX(W_,66) = GetVector(x__, 2);
DYNX(W_,64) = GetVector(x__, 3);
DYNX(W_,62) = GetVector(x__, 4);
DYNX(W_,44) = GetVector(x__, 5);
EndNonLinearSystemOfEquationsNH(residue__, x__, 1);
DYNNonlinearSolverStatistics(0, DYNX(W_,78), DYNX(W_,79), DYNX(W_,80), 
  DYNX(W_,81));
 /* End of Non-Linear Equation Block */ }



DYNX(W_,53) = DYNX(W_,60)+DYNX(W_,62)+DYNX(W_,64)+DYNX(W_,66)+DYNX(W_,68);
DYNX(W_,24) = IF LessTime(0.5, 0) THEN 50 ELSE 100;

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,142) = (PushModelContext(1,"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[2].numeric_pump.fluidPortIn.p)")
  nLSystem_numericx_0pump_CalcDensityx_0Unique2(DYNX(W_,52)));
PopModelContext();
DYNX(DYNhelp,143) = divinvGuarded(DYNX(DYNhelp,142),"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[2].numeric_pump.fluidPortIn.p)");
DYNX(W_,56) = DYNX(DYNhelp,143)*DYNX(DP_,28);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
if (NewParameters_) {
DYNX(DYNhelp,144) = divinvGuarded(DYNX(DP_,43),"nLSystem[3].volume.M");
}
DYNX(W_,69) = RememberSimple_(DYNX(W_,69), 7);
SolveScalarLinearParametric(DYNX(DP_,40),"nLSystem[3].volume.V", 
  DYNX(DYNhelp,144)*DYNX(X_,2)*8.31446261815324*DYNX(DP_,42),"nLSystem[3].volume.m*8.31446261815324*nLSystem[3].volume.T/nLSystem[3].volume.M",
   DYNX(W_,69),"nLSystem[3].volume.p");
 /* End of Equation Block */ 


{ /* Non-linear system of equations to solve. */
/* Tag: simulation.nonlinear[2] */
/* Introducing 11 common subexpressions and reusing 1 variables totally whereof 12
   are global used in 3 expressions */
/* Of the common subexpressions 12 are reals, 0 are integers, and 0
   are booleans. */
const char*const varnames_[]={"nLSystem[3].parallelResistors.pressureLossTube[3].mdot",
   "nLSystem[3].parallelResistors.pressureLossTube[2].mdot", "nLSystem[2].numeric_pump.vdot"};
const double nominal_[]={100.0, 100.0, 1.0};
static const int sJacobianCG_[1] = {-1};
static const struct QJacobianTag_ sJacobianGC2_[1] = {{-1,0}};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 3, 0, 1, 2, 7, 4, 
  DYNX(DYNhelp,145), 76, DYNX(did_->helpvari_vec,27), 25);
NonLinearSystemSave(DYNX(W_,56), 0);
NonLinearSystemSave(DYNX(W_,24), 1);
NonLinearSystemSave(DYNX(W_,52), 2);
NonLinearSystemSave(DYNX(W_,69), 3);
SetInitVectorNH(x__, 1, DYNX(W_,77), Remember_(DYNX(W_,77), 8));
SetInitVectorNH(x__, 2, DYNX(W_,75), Remember_(DYNX(W_,75), 9));
SetInitVectorNH(x__, 3, DYNX(W_,55), Remember_(DYNX(W_,55), 10));
Residues;
  if (NewParameters_) {
  DYNX(DYNhelp,221) = divinvGuarded(DYNX(DP_,29),"nLSystem[2].numeric_pump.n_nom");
  }
  DYNX(DYNhelp,222) = DYNX(W_,55)*DYNX(DP_,29);
  DYNX(DYNhelp,223) = DYNX(W_,56)*DYNX(W_,24);
  DYNX(DYNhelp,224) = divGuarded(DYNX(DYNhelp,222),"nLSystem[2].numeric_pump.vdot*nLSystem[2].numeric_pump.n_nom",
    DYNX(DYNhelp,223),"nLSystem[2].numeric_pump.vdot_nom*nLSystem[2].numeric_pump.n");
  DYNX(W_,54) = sqr(DYNX(DYNhelp,221)*DYNX(W_,24))*(1-sqr(DYNX(DYNhelp,224)))*
    DYNX(DP_,27);
  DYNX(W_,57) = DYNX(W_,52)+DYNX(W_,54);
  DYNX(W_,76) = DYNX(W_,57)-DYNX(W_,69);
  DYNX(W_,74) = DYNX(W_,76);
  DYNX(W_,72) = DYNX(W_,76);
  DYNX(DYNhelp,225) = (PushModelContext(1,"nLSystem.numeric_pump.CalcDensity_Unique2(nLSystem[2].numeric_pump.fluidPortOut.p)")
    nLSystem_numericx_0pump_CalcDensityx_0Unique2(DYNX(W_,57)));
  PopModelContext();
  DYNX(W_,58) =  -DYNX(W_,55)*DYNX(DYNhelp,225);
  DYNX(W_,73) =  -(DYNX(W_,58)+DYNX(W_,75)+DYNX(W_,77));
if (NewParameters_) {
DYNX(DYNhelp,226) = divinvGuarded(DYNX(DP_,47),"nLSystem[3].parallelResistors.pressureLossTube[1].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,227) = divinvGuarded(DYNX(DP_,48),"nLSystem[3].parallelResistors.pressureLossTube[1].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,228) = divinvGuarded(DYNX(DP_,49),"nLSystem[3].parallelResistors.pressureLossTube[2].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,229) = divinvGuarded(DYNX(DP_,50),"nLSystem[3].parallelResistors.pressureLossTube[2].mdot_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,230) = divinvGuarded(DYNX(DP_,51),"nLSystem[3].parallelResistors.pressureLossTube[3].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,231) = divinvGuarded(DYNX(DP_,52),"nLSystem[3].parallelResistors.pressureLossTube[3].mdot_nom");
}
SetVector(residue__, 1, DYNX(DYNhelp,226)*DYNX(W_,72)-powUnguarded(
  DYNX(DYNhelp,227)*DYNX(W_,73), 3));
SetVector(residue__, 2, DYNX(DYNhelp,228)*DYNX(W_,74)-powUnguarded(
  DYNX(DYNhelp,229)*DYNX(W_,75), 3));
SetVector(residue__, 3, DYNX(DYNhelp,230)*DYNX(W_,76)-powUnguarded(
  DYNX(DYNhelp,231)*DYNX(W_,77), 3));

{ /* No analytic Jacobian available*/
SolveNonLinearSystemOfEquationsNH(Jacobian__, 0, 0, 0, residue__, x__, 2, 
  "Tag: simulation.nonlinear[2]");
DYNX(W_,77) = GetVector(x__, 1);
DYNX(W_,75) = GetVector(x__, 2);
DYNX(W_,55) = GetVector(x__, 3);
EndNonLinearSystemOfEquationsNH(residue__, x__, 2);
DYNNonlinearSolverStatistics(1, DYNX(W_,82), DYNX(W_,83), DYNX(W_,84), 
  DYNX(W_,85));
 /* End of Non-Linear Equation Block */ }



DYNX(F_,1) = DYNX(W_,53)+DYNX(W_,58);

{ /* Non-linear system of equations to solve. */
/* Tag: simulation.nonlinear[3] */
/* Introducing 15 common subexpressions and reusing 1 variables totally whereof 12
   are global used in 20 expressions */
/* Of the common subexpressions 16 are reals, 0 are integers, and 0
   are booleans. */
const char*const varnames_[]={"nLSystem[1].parallelResistors.pressureLossTube[2].mdot",
   "nLSystem[1].parallelResistors.pressureLossTube[1].mdot"};
const double nominal_[]={100.0, 100.0};
static const int sJacobianCG_[1] = {-1};
static const struct QJacobianTag_ sJacobianGC2_[1] = {{-1,0}};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 2, 0, 0, 3, 10, 1, 
  DYNX(DYNhelp,232), 51, DYNX(did_->helpvari_vec,52), 24);
NonLinearSystemSave(DYNX(W_,41), 0);
SetInitVectorNH(x__, 1, DYNX(W_,51), Remember_(DYNX(W_,51), 11));
SetInitVectorNH(x__, 2, DYNX(W_,49), Remember_(DYNX(W_,49), 12));
Residues;
  DYNX(W_,38) = DYNX(W_,49)+DYNX(W_,51);
  if (NewParameters_) {
  DYNX(DYNhelp,283) = divinvGuarded(DYNX(DP_,10),"pressureIncreasePump3.n_nom");
  }
  if (NewParameters_) {
  DYNX(DYNhelp,284) = sqr(DYNX(DYNhelp,283)*100);
  }
  DYNX(DYNhelp,285) = DYNX(W_,38)*DYNX(DP_,10);
  if (NewParameters_) {
  DYNX(DYNhelp,286) = 100*DYNX(DP_,9);
  }
  if (NewParameters_) {
  DYNX(DYNhelp,287) = divinvGuarded(DYNX(DYNhelp,286),"100*pressureIncreasePump3.vdot_nom");
  }
  DYNX(DYNhelp,288) = DYNX(DYNhelp,287)*DYNX(DYNhelp,285);
  DYNX(W_,37) = DYNX(DYNhelp,284)*(1-sqr(DYNX(DYNhelp,288)))*DYNX(DP_,8);
  DYNX(W_,48) = DYNX(DP_,11)-DYNX(W_,41)+DYNX(W_,37);
  if (NewParameters_) {
  DYNX(DYNhelp,289) = divinvGuarded(DYNX(DP_,22),"nLSystem[1].parallelResistors.pressureLossTube[2].mdot_nom");
  }
  DYNX(DYNhelp,290) = DYNX(DYNhelp,289)*DYNX(W_,51);
  DYNX(W_,50) = powUnguarded(DYNX(DYNhelp,290), 3)*DYNX(DP_,21);
if (NewParameters_) {
DYNX(DYNhelp,291) = divinvGuarded(DYNX(DP_,19),"nLSystem[1].parallelResistors.pressureLossTube[1].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,292) = divinvGuarded(DYNX(DP_,20),"nLSystem[1].parallelResistors.pressureLossTube[1].mdot_nom");
}
DYNX(DYNhelp,293) = DYNX(DYNhelp,292)*DYNX(W_,49);
SetVector(residue__, 1, DYNX(W_,50)-DYNX(W_,48));
SetVector(residue__, 2, DYNX(DYNhelp,291)*DYNX(W_,48)-powUnguarded(
  DYNX(DYNhelp,293), 3));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
DYNX(DYNhelp,294) = DYNX(DYNhelp,284)*DYNX(DYNhelp,285)*DYNX(DP_,10);
DYNX(DYNhelp,295) = DYNX(DP_,8)*DYNX(DYNhelp,294);
DYNX(DYNhelp,296) = DYNX(DYNhelp,287)*DYNX(DYNhelp,287)*(-2.0)*DYNX(DYNhelp,295);
DYNX(DYNhelp,297) = DYNX(DYNhelp,291)*DYNX(DYNhelp,287)*DYNX(DYNhelp,287)*2.0*
  DYNX(DYNhelp,295);
SetMatrixLeading(Jacobian__, 1, 1, 2, DYNX(DYNhelp,289)*3.0*DYNX(DP_,21)*sqr(
  DYNX(DYNhelp,290))-DYNX(DYNhelp,296));
SetMatrixLeading(Jacobian__, 1, 2, 2,  -DYNX(DYNhelp,296));
SetMatrixLeading(Jacobian__, 2, 1, 2,  -DYNX(DYNhelp,297));
SetMatrixLeading(Jacobian__, 2, 2, 2,  -(DYNX(DYNhelp,292)*3*sqr(
  DYNX(DYNhelp,293))+DYNX(DYNhelp,297)));

SolveNonLinearSystemOfEquationsNH(Jacobian__, 0, 0, 0, residue__, x__, 3, 
  "Tag: simulation.nonlinear[3]");
DYNX(W_,51) = GetVector(x__, 1);
DYNX(W_,49) = GetVector(x__, 2);
EndNonLinearSystemOfEquationsNH(residue__, x__, 3);
DYNNonlinearSolverStatistics(2, DYNX(W_,86), DYNX(W_,87), DYNX(W_,88), 
  DYNX(W_,89));
 /* End of Non-Linear Equation Block */ }



DYNX(W_,39) = DYNX(W_,41)+DYNX(W_,50);
DYNX(W_,42) = DYNX(W_,49)+DYNX(W_,51);
DYNX(F_,0) = DYNX(W_,42)+DYNX(W_,47);
DYNX(W_,70) = DYNX(W_,73)+DYNX(W_,75)+DYNX(W_,77);
DYNX(W_,25) = IF LessTime(0.5, 0) THEN 50 ELSE 100;

{ /* Non-linear system of equations to solve. */
/* Tag: simulation.nonlinear[4] */
/* Introducing 20 common subexpressions whereof 17 are global used in 27
   expressions */
/* Of the common subexpressions 20 are reals, 0 are integers, and 0
   are booleans. */
const char*const varnames_[]={"parallelResistors.pressureLossTube[4].mdot", 
  "parallelResistors.pressureLossTube[3].mdot", "parallelResistors.pressureLossTube[2].mdot",
   "parallelResistors.pressureLossTube[1].mdot"};
const double nominal_[]={100.0, 100.0, 100.0, 100.0};
static const int sJacobianCG_[1] = {-1};
static const struct QJacobianTag_ sJacobianGC2_[1] = {{-1,0}};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 4, 0, 0, 4, 12, 2, 
  DYNX(DYNhelp,298), 94, DYNX(did_->helpvari_vec,76), 26);
NonLinearSystemSave(DYNX(W_,25), 0);
NonLinearSystemSave(DYNX(W_,69), 1);
SetInitVectorNH(x__, 1, DYNX(W_,33), Remember_(DYNX(W_,33), 13));
SetInitVectorNH(x__, 2, DYNX(W_,31), Remember_(DYNX(W_,31), 14));
SetInitVectorNH(x__, 3, DYNX(W_,29), Remember_(DYNX(W_,29), 15));
SetInitVectorNH(x__, 4, DYNX(W_,27), Remember_(DYNX(W_,27), 16));
Residues;
  DYNX(W_,36) = DYNX(W_,27)+DYNX(W_,29)+DYNX(W_,31)+DYNX(W_,33);
  if (NewParameters_) {
  DYNX(DYNhelp,392) = divinvGuarded(DYNX(DP_,1),"parallelResistors.pressureLossTube[1].mdot_nom");
  }
  DYNX(DYNhelp,393) = DYNX(DYNhelp,392)*DYNX(W_,27);
  DYNX(W_,26) = powUnguarded(DYNX(DYNhelp,393), 3)*DYNX(DP_,0);
  if (NewParameters_) {
  DYNX(DYNhelp,394) = divinvGuarded(DYNX(DP_,3),"parallelResistors.pressureLossTube[2].mdot_nom");
  }
  DYNX(DYNhelp,395) = DYNX(DYNhelp,394)*DYNX(W_,29);
  DYNX(W_,28) = powUnguarded(DYNX(DYNhelp,395), 3)*DYNX(DP_,2);
  DYNX(W_,71) = DYNX(W_,28)-DYNX(W_,69)+DYNX(DP_,11);
if (NewParameters_) {
DYNX(DYNhelp,396) = divinvGuarded(DYNX(DP_,4),"parallelResistors.pressureLossTube[3].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,397) = divinvGuarded(DYNX(DP_,5),"parallelResistors.pressureLossTube[3].mdot_nom");
}
DYNX(DYNhelp,398) = DYNX(DYNhelp,397)*DYNX(W_,31);
if (NewParameters_) {
DYNX(DYNhelp,399) = divinvGuarded(DYNX(DP_,6),"parallelResistors.pressureLossTube[4].delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,400) = divinvGuarded(DYNX(DP_,7),"parallelResistors.pressureLossTube[4].mdot_nom");
}
DYNX(DYNhelp,401) = DYNX(DYNhelp,400)*DYNX(W_,33);
if (NewParameters_) {
DYNX(DYNhelp,402) = divinvGuarded(DYNX(DP_,44),"nLSystem[3].analytic_pump.delta_p_nom");
}
if (NewParameters_) {
DYNX(DYNhelp,403) = divinvGuarded(DYNX(DP_,46),"nLSystem[3].analytic_pump.n_nom");
}
DYNX(DYNhelp,404) = sqr(DYNX(DYNhelp,403)*DYNX(W_,25));
DYNX(DYNhelp,405) = DYNX(W_,36)*DYNX(DP_,46);
DYNX(DYNhelp,406) = DYNX(DP_,45)*DYNX(W_,25);
DYNX(DYNhelp,407) = divinvGuarded(DYNX(DYNhelp,406),"nLSystem[3].analytic_pump.vdot_nom*nLSystem[3].analytic_pump.n");
DYNX(DYNhelp,408) = DYNX(DYNhelp,407)*DYNX(DYNhelp,405);
SetVector(residue__, 1, DYNX(W_,26)-(DYNX(W_,69)-DYNX(DP_,11)+DYNX(W_,71)));
SetVector(residue__, 2, DYNX(DYNhelp,396)*DYNX(W_,28)-powUnguarded(
  DYNX(DYNhelp,398), 3));
SetVector(residue__, 3, DYNX(DYNhelp,399)*DYNX(W_,28)-powUnguarded(
  DYNX(DYNhelp,401), 3));
SetVector(residue__, 4, DYNX(DYNhelp,402)*DYNX(W_,71)-DYNX(DYNhelp,404)*(1-sqr(
  DYNX(DYNhelp,408))));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
DYNX(DYNhelp,409) = DYNX(DP_,2)*sqr(DYNX(DYNhelp,395));
DYNX(DYNhelp,410) = 3.0*DYNX(DYNhelp,409);
DYNX(DYNhelp,411) = DYNX(DYNhelp,407)*DYNX(DYNhelp,407)*2.0*DYNX(DYNhelp,404)*
  DYNX(DYNhelp,405)*DYNX(DP_,46);
SetMatrixLeading(Jacobian__, 1, 3, 4, DYNX(DYNhelp,394)*(-3.0)*DYNX(DYNhelp,409));
SetMatrixLeading(Jacobian__, 1, 4, 4, DYNX(DYNhelp,392)*3.0*DYNX(DP_,0)*sqr(
  DYNX(DYNhelp,393)));
SetMatrixLeading(Jacobian__, 2, 2, 4,  -DYNX(DYNhelp,397)*3*sqr(DYNX(DYNhelp,398)));
SetMatrixLeading(Jacobian__, 2, 3, 4, DYNX(DYNhelp,394)*DYNX(DYNhelp,396)*
  DYNX(DYNhelp,410));
SetMatrixLeading(Jacobian__, 3, 1, 4,  -DYNX(DYNhelp,400)*3*sqr(DYNX(DYNhelp,401)));
SetMatrixLeading(Jacobian__, 3, 3, 4, DYNX(DYNhelp,394)*DYNX(DYNhelp,399)*
  DYNX(DYNhelp,410));
SetMatrixLeading(Jacobian__, 4, 1, 4, DYNX(DYNhelp,411));
SetMatrixLeading(Jacobian__, 4, 2, 4, DYNX(DYNhelp,411));
SetMatrixLeading(Jacobian__, 4, 3, 4, DYNX(DYNhelp,411)+DYNX(DYNhelp,394)*
  DYNX(DYNhelp,402)*DYNX(DYNhelp,410));
SetMatrixLeading(Jacobian__, 4, 4, 4, DYNX(DYNhelp,411));

SolveNonLinearSystemOfEquationsNH(Jacobian__, 0, 0, 0, residue__, x__, 4, 
  "Tag: simulation.nonlinear[4]");
DYNX(W_,33) = GetVector(x__, 1);
DYNX(W_,31) = GetVector(x__, 2);
DYNX(W_,29) = GetVector(x__, 3);
DYNX(W_,27) = GetVector(x__, 4);
EndNonLinearSystemOfEquationsNH(residue__, x__, 4);
DYNNonlinearSolverStatistics(3, DYNX(W_,90), DYNX(W_,91), DYNX(W_,92), 
  DYNX(W_,93));
 /* End of Non-Linear Equation Block */ }



DYNX(W_,30) = DYNX(W_,28);
DYNX(W_,32) = DYNX(W_,28);
DYNX(W_,35) = DYNX(DP_,11)+DYNX(W_,32);
DYNX(F_,2) = DYNX(W_,70)-DYNX(W_,36);

AcceptedSection1

AcceptedSection2
DYNX(W_,34) =  -(DYNX(W_,27)+DYNX(W_,29)+DYNX(W_,31)+DYNX(W_,33));
DYNX(W_,40) =  -(DYNX(W_,34)+DYNX(W_,38));

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include "dsblock6.c"

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("numNLequations[1]", "sizes of each nonlinear system of equations [:#(type=Integer)]",\
 0, 2, 0.0,0.0,0.0,0,517)
DeclareVariable("numNLequations[2]", "sizes of each nonlinear system of equations [:#(type=Integer)]",\
 1, 5, 0.0,0.0,0.0,0,517)
DeclareVariable("numNLequations[3]", "sizes of each nonlinear system of equations [:#(type=Integer)]",\
 2, 3, 0.0,0.0,0.0,0,517)
DeclareVariable("numNLequations[4]", "sizes of each nonlinear system of equations [:#(type=Integer)]",\
 3, 4, 0.0,0.0,0.0,0,517)
DeclareVariable("numJacobians", "number of numerical Jacobians to be inserted (maximum: number of nonlinear equation systems -1) [:#(type=Integer)]",\
 4, 2, 0.0,0.0,0.0,0,517)
DeclareVariable("parallelResistors.nParallel", "[:#(type=Integer)]", 5, 4, \
0.0,0.0,0.0,0,517)
DeclareVariable("parallelResistors.pressureLossTube[1].delta_p", \
"pressure drop in tube [Pa]", 26, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("parallelResistors.pressureLossTube[1].mdot", "mass flow rate [kg/s]",\
 27, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("parallelResistors.pressureLossTube[1].delta_p_nom", \
"pressure drop at nominal mass flow", 0, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("parallelResistors.pressureLossTube[1].mdot_nom", \
"nominal mass flow", 1, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("parallelResistors.pressureLossTube[1].fluidPortIn.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "parallelResistors.fluidPortIn.p", 1,\
 5, 35, 4)
DeclareAlias2("parallelResistors.pressureLossTube[1].fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[1].mdot", 1, 5, 27, 132)
DeclareAlias2("parallelResistors.pressureLossTube[1].fluidPortOut.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "boundary_Pressure.p", 1,\
 7, 11, 4)
DeclareAlias2("parallelResistors.pressureLossTube[1].fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[1].mdot", -1, 5, 27, 132)
DeclareVariable("parallelResistors.pressureLossTube[2].delta_p", \
"pressure drop in tube [Pa]", 28, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("parallelResistors.pressureLossTube[2].mdot", "mass flow rate [kg/s]",\
 29, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("parallelResistors.pressureLossTube[2].delta_p_nom", \
"pressure drop at nominal mass flow", 2, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("parallelResistors.pressureLossTube[2].mdot_nom", \
"nominal mass flow", 3, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("parallelResistors.pressureLossTube[2].fluidPortIn.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "parallelResistors.fluidPortIn.p", 1,\
 5, 35, 4)
DeclareAlias2("parallelResistors.pressureLossTube[2].fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[2].mdot", 1, 5, 29, 132)
DeclareAlias2("parallelResistors.pressureLossTube[2].fluidPortOut.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "boundary_Pressure.p", 1,\
 7, 11, 4)
DeclareAlias2("parallelResistors.pressureLossTube[2].fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[2].mdot", -1, 5, 29, 132)
DeclareVariable("parallelResistors.pressureLossTube[3].delta_p", \
"pressure drop in tube [Pa]", 30, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("parallelResistors.pressureLossTube[3].mdot", "mass flow rate [kg/s]",\
 31, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("parallelResistors.pressureLossTube[3].delta_p_nom", \
"pressure drop at nominal mass flow", 4, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("parallelResistors.pressureLossTube[3].mdot_nom", \
"nominal mass flow", 5, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("parallelResistors.pressureLossTube[3].fluidPortIn.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "parallelResistors.fluidPortIn.p", 1,\
 5, 35, 4)
DeclareAlias2("parallelResistors.pressureLossTube[3].fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[3].mdot", 1, 5, 31, 132)
DeclareAlias2("parallelResistors.pressureLossTube[3].fluidPortOut.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "boundary_Pressure.p", 1,\
 7, 11, 4)
DeclareAlias2("parallelResistors.pressureLossTube[3].fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[3].mdot", -1, 5, 31, 132)
DeclareVariable("parallelResistors.pressureLossTube[4].delta_p", \
"pressure drop in tube [Pa]", 32, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("parallelResistors.pressureLossTube[4].mdot", "mass flow rate [kg/s]",\
 33, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("parallelResistors.pressureLossTube[4].delta_p_nom", \
"pressure drop at nominal mass flow", 6, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("parallelResistors.pressureLossTube[4].mdot_nom", \
"nominal mass flow", 7, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("parallelResistors.pressureLossTube[4].fluidPortIn.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "parallelResistors.fluidPortIn.p", 1,\
 5, 35, 4)
DeclareAlias2("parallelResistors.pressureLossTube[4].fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[4].mdot", 1, 5, 33, 132)
DeclareAlias2("parallelResistors.pressureLossTube[4].fluidPortOut.p", \
"Thermodynamic pressure in the connection point [Pa|bar]", "boundary_Pressure.p", 1,\
 7, 11, 4)
DeclareAlias2("parallelResistors.pressureLossTube[4].fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"parallelResistors.pressureLossTube[4].mdot", -1, 5, 33, 132)
DeclareAlias2("parallelResistors.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "boundary_Pressure.p", 1, 7, 11, 4)
DeclareVariable("parallelResistors.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 34, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("parallelResistors.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 35, 0.0, 0.0,1.7976931348623157E+308,100000.0,0,520)
DeclareVariable("parallelResistors.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 36, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("realExpression.y", "Value of Real output", 6, 100, 0.0,0.0,0.0,\
0,513)
DeclareVariable("pressureIncreasePump3.delta_p", "pressure difference between inlet and outlet [Pa]",\
 37, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("pressureIncreasePump3.mdot", "mass flow through pump [kg/s]", 38,\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pressureIncreasePump3.vdot", "volume flow through pump", \
"pressureIncreasePump3.mdot", 1, 5, 38, 0)
DeclareParameter("pressureIncreasePump3.delta_p_nom", "nominal pressure increase in pump",\
 8, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("pressureIncreasePump3.mdot_nom", "nominal mass flow art nominal pressure increase",\
 9, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("pressureIncreasePump3.vdot_nom", "nominal volume flow", \
"pressureIncreasePump3.mdot_nom", 1, 7, 9, 0)
DeclareParameter("pressureIncreasePump3.n_nom", "nominal rotational speed", 10, 10,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("pressureIncreasePump3.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "boundary_Pressure.p", 1, 7, 11, 4)
DeclareAlias2("pressureIncreasePump3.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "pressureIncreasePump3.mdot", 1, 5, 38, 132)
DeclareVariable("pressureIncreasePump3.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 39, 0.0, 0.0,1.7976931348623157E+308,100000.0,0,520)
DeclareAlias2("pressureIncreasePump3.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "pressureIncreasePump3.mdot", -1, 5, 38, 132)
DeclareVariable("pressureIncreasePump3.n", "rotational speed of pump", 7, 100, \
0.0,0.0,0.0,0,513)
DeclareParameter("boundary_Pressure.p", "pressure boundary value [Pa|bar]", 11, 101300,\
 0.0,1.7976931348623157E+308,100000.0,0,560)
DeclareVariable("boundary_Pressure.allow_massflow", "is mass flow allowed across the boundary [:#(type=Boolean)]",\
 8, true, 0.0,0.0,0.0,0,515)
DeclareAlias2("boundary_Pressure.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "boundary_Pressure.p", 1, 7, 11, 4)
DeclareVariable("boundary_Pressure.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 40, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("numNLequationSystems", "[:#(type=Integer)]", 9, 4, 0.0,0.0,0.0,\
0,2565)
DeclareVariable("numberNumericJacobians", "[:#(type=Integer)]", 10, 2, 0.0,0.0,\
0.0,0,2565)
DeclareVariable("insertJacobian[1]", "[:#(type=Boolean)]", 11, true, 0.0,0.0,0.0,\
0,2563)
DeclareVariable("insertJacobian[2]", "[:#(type=Boolean)]", 12, true, 0.0,0.0,0.0,\
0,2563)
DeclareVariable("insertJacobian[3]", "[:#(type=Boolean)]", 13, false, 0.0,0.0,\
0.0,0,2563)
DeclareVariable("nLSystem[1].numNLequations", "[:#(type=Integer)]", 14, 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[1].withNumericJacobian", "[:#(type=Boolean)]", 15, \
true, 0.0,0.0,0.0,0,515)
DeclareParameter("nLSystem[1].volume.V", "Volume [m3]", 12, 1, 0.0,0.0,0.0,0,560)
DeclareState("nLSystem[1].volume.m", "mass of Medium in Volume [kg]", 0, 0.0, \
0.0,1.7976931348623157E+308,0.0,0,544)
DeclareDerivative("nLSystem[1].volume.der(m)", "der(mass of Medium in Volume) [kg/s]",\
 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("nLSystem[1].volume.p", "pressure of volume [Pa|bar]", 41, 0.0, \
0.0,1.7976931348623157E+308,100000.0,0,512)
DeclareParameter("nLSystem[1].volume.p_start", "initial pressure [Pa|bar]", 13, 101300,\
 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[1].volume.T", "fixed Temperature [K|degC]", 14, \
298.15, 0.0,1.7976931348623157E+308,300.0,0,560)
DeclareParameter("nLSystem[1].volume.M", "molar mass of medium (value for air)",\
 15, 0.028964, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[1].volume.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].volume.p", 1, 5, 41, 4)
DeclareVariable("nLSystem[1].volume.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 42, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("nLSystem[1].volume.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].volume.p", 1, 5, 41, 4)
DeclareAlias2("nLSystem[1].volume.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[1].fluidPortOut.m_flow", 1, 5, 47, 132)
DeclareVariable("nLSystem[1].numeric_pump.delta_p", "pressure difference between inlet and outlet [Pa]",\
 43, 0.0, 0.0,0.0,100000.0,0,512)
DeclareAlias2("nLSystem[1].numeric_pump.mdot", "mass flow through pump [kg/s]", \
"nLSystem[1].fluidPortOut.m_flow", -1, 5, 47, 0)
DeclareVariable("nLSystem[1].numeric_pump.vdot", "volume flow through pump", 44,\
 0.0, 0.0,0.0,0.0,0,576)
DeclareParameter("nLSystem[1].numeric_pump.delta_p_nom", "nominal pressure increase in pump",\
 16, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[1].numeric_pump.mdot_nom", "nominal mass flow art nominal pressure increase",\
 17, 0.5, 0.0,0.0,0.0,0,560)
DeclareVariable("nLSystem[1].numeric_pump.vdot_nom", "nominal volume flow", 45, \
0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("nLSystem[1].numeric_pump.n_nom", "nominal rotational speed", 18,\
 10, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[1].numeric_pump.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].volume.p", 1, 5, 41, 4)
DeclareAlias2("nLSystem[1].numeric_pump.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[1].fluidPortOut.m_flow", -1, 5, 47, 132)
DeclareAlias2("nLSystem[1].numeric_pump.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].fluidPortOut.p", 1, 5, 46, 4)
DeclareAlias2("nLSystem[1].numeric_pump.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[1].fluidPortOut.m_flow", 1, 5, 47, 132)
DeclareAlias2("nLSystem[1].numeric_pump.n", "rotational speed of pump", \
"nLSystem[1].realExpression1.y", 1, 5, 23, 0)
DeclareVariable("nLSystem[1].realExpression1.y", "Value of Real output", 23, 0.0,\
 0.0,0.0,0.0,0,640)
DeclareVariable("nLSystem[1].fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 46, 0.0, 0.0,1.7976931348623157E+308,100000.0,0,520)
DeclareVariable("nLSystem[1].fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 47, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("nLSystem[1].fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "pressureIncreasePump3.fluidPortOut.p", 1, 5, 39, 4)
DeclareAlias2("nLSystem[1].fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "pressureIncreasePump3.mdot", 1, 5, 38, 132)
DeclareVariable("nLSystem[1].parallelResistors.nParallel", "[:#(type=Integer)]",\
 16, 2, 0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[1].parallelResistors.pressureLossTube[1].delta_p", \
"pressure drop in tube [Pa]", 48, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[1].parallelResistors.pressureLossTube[1].mdot", \
"mass flow rate [kg/s]", 49, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[1].parallelResistors.pressureLossTube[1].delta_p_nom",\
 "pressure drop at nominal mass flow", 19, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[1].parallelResistors.pressureLossTube[1].mdot_nom", \
"nominal mass flow", 20, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[1].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "pressureIncreasePump3.fluidPortOut.p", 1,\
 5, 39, 4)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[1].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].parallelResistors.pressureLossTube[1].mdot", 1, 5, 49, 132)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[1].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].volume.p", 1,\
 5, 41, 4)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[1].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].parallelResistors.pressureLossTube[1].mdot", -1, 5, 49, 132)
DeclareVariable("nLSystem[1].parallelResistors.pressureLossTube[2].delta_p", \
"pressure drop in tube [Pa]", 50, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[1].parallelResistors.pressureLossTube[2].mdot", \
"mass flow rate [kg/s]", 51, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[1].parallelResistors.pressureLossTube[2].delta_p_nom",\
 "pressure drop at nominal mass flow", 21, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[1].parallelResistors.pressureLossTube[2].mdot_nom", \
"nominal mass flow", 22, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[2].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "pressureIncreasePump3.fluidPortOut.p", 1,\
 5, 39, 4)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[2].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].parallelResistors.pressureLossTube[2].mdot", 1, 5, 51, 132)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[2].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].volume.p", 1,\
 5, 41, 4)
DeclareAlias2("nLSystem[1].parallelResistors.pressureLossTube[2].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].parallelResistors.pressureLossTube[2].mdot", -1, 5, 51, 132)
DeclareAlias2("nLSystem[1].parallelResistors.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].volume.p", 1, 5, 41, 4)
DeclareAlias2("nLSystem[1].parallelResistors.fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].volume.fluidPortIn.m_flow", -1, 5, 42, 132)
DeclareAlias2("nLSystem[1].parallelResistors.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "pressureIncreasePump3.fluidPortOut.p", 1, 5, 39, 4)
DeclareAlias2("nLSystem[1].parallelResistors.fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"pressureIncreasePump3.mdot", 1, 5, 38, 132)
DeclareVariable("nLSystem[2].numNLequations", "[:#(type=Integer)]", 17, 5, \
0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[2].withNumericJacobian", "[:#(type=Boolean)]", 18, \
true, 0.0,0.0,0.0,0,515)
DeclareParameter("nLSystem[2].volume.V", "Volume [m3]", 23, 1, 0.0,0.0,0.0,0,560)
DeclareState("nLSystem[2].volume.m", "mass of Medium in Volume [kg]", 1, 0.0, \
0.0,1.7976931348623157E+308,0.0,0,544)
DeclareDerivative("nLSystem[2].volume.der(m)", "der(mass of Medium in Volume) [kg/s]",\
 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("nLSystem[2].volume.p", "pressure of volume [Pa|bar]", 52, 0.0, \
0.0,1.7976931348623157E+308,100000.0,0,512)
DeclareParameter("nLSystem[2].volume.p_start", "initial pressure [Pa|bar]", 24, 101300,\
 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].volume.T", "fixed Temperature [K|degC]", 25, \
298.15, 0.0,1.7976931348623157E+308,300.0,0,560)
DeclareParameter("nLSystem[2].volume.M", "molar mass of medium (value for air)",\
 26, 0.028964, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].volume.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].volume.p", 1, 5, 52, 4)
DeclareVariable("nLSystem[2].volume.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 53, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("nLSystem[2].volume.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].volume.p", 1, 5, 52, 4)
DeclareAlias2("nLSystem[2].volume.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[2].fluidPortOut.m_flow", 1, 5, 58, 132)
DeclareVariable("nLSystem[2].numeric_pump.delta_p", "pressure difference between inlet and outlet [Pa]",\
 54, 0.0, 0.0,0.0,100000.0,0,512)
DeclareAlias2("nLSystem[2].numeric_pump.mdot", "mass flow through pump [kg/s]", \
"nLSystem[2].fluidPortOut.m_flow", -1, 5, 58, 0)
DeclareVariable("nLSystem[2].numeric_pump.vdot", "volume flow through pump", 55,\
 0.0, 0.0,0.0,0.0,0,576)
DeclareParameter("nLSystem[2].numeric_pump.delta_p_nom", "nominal pressure increase in pump",\
 27, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].numeric_pump.mdot_nom", "nominal mass flow art nominal pressure increase",\
 28, 0.5, 0.0,0.0,0.0,0,560)
DeclareVariable("nLSystem[2].numeric_pump.vdot_nom", "nominal volume flow", 56, \
0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("nLSystem[2].numeric_pump.n_nom", "nominal rotational speed", 29,\
 10, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].numeric_pump.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].volume.p", 1, 5, 52, 4)
DeclareAlias2("nLSystem[2].numeric_pump.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[2].fluidPortOut.m_flow", -1, 5, 58, 132)
DeclareAlias2("nLSystem[2].numeric_pump.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].fluidPortOut.p", 1, 5, 57, 4)
DeclareAlias2("nLSystem[2].numeric_pump.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[2].fluidPortOut.m_flow", 1, 5, 58, 132)
DeclareAlias2("nLSystem[2].numeric_pump.n", "rotational speed of pump", \
"nLSystem[2].realExpression1.y", 1, 5, 24, 0)
DeclareVariable("nLSystem[2].realExpression1.y", "Value of Real output", 24, 0.0,\
 0.0,0.0,0.0,0,640)
DeclareVariable("nLSystem[2].fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 57, 0.0, 0.0,1.7976931348623157E+308,100000.0,0,520)
DeclareVariable("nLSystem[2].fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 58, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("nLSystem[2].fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].fluidPortOut.p", 1, 5, 46, 4)
DeclareAlias2("nLSystem[2].fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[1].fluidPortOut.m_flow", -1, 5, 47, 132)
DeclareVariable("nLSystem[2].parallelResistors.nParallel", "[:#(type=Integer)]",\
 19, 5, 0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[1].delta_p", \
"pressure drop in tube [Pa]", 59, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[1].mdot", \
"mass flow rate [kg/s]", 60, 0.01, 0.0,0.0,100.0,0,512)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[1].delta_p_nom",\
 "pressure drop at nominal mass flow", 30, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[1].mdot_nom", \
"nominal mass flow", 31, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[1].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].fluidPortOut.p", 1,\
 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[1].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[1].mdot", 1, 5, 60, 132)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[1].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].volume.p", 1,\
 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[1].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[1].mdot", -1, 5, 60, 132)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[2].delta_p", \
"pressure drop in tube [Pa]", 61, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[2].mdot", \
"mass flow rate [kg/s]", 62, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[2].delta_p_nom",\
 "pressure drop at nominal mass flow", 32, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[2].mdot_nom", \
"nominal mass flow", 33, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[2].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].fluidPortOut.p", 1,\
 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[2].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[2].mdot", 1, 5, 62, 132)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[2].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].volume.p", 1,\
 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[2].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[2].mdot", -1, 5, 62, 132)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[3].delta_p", \
"pressure drop in tube [Pa]", 63, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[3].mdot", \
"mass flow rate [kg/s]", 64, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[3].delta_p_nom",\
 "pressure drop at nominal mass flow", 34, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[3].mdot_nom", \
"nominal mass flow", 35, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[3].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].fluidPortOut.p", 1,\
 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[3].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[3].mdot", 1, 5, 64, 132)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[3].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].volume.p", 1,\
 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[3].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[3].mdot", -1, 5, 64, 132)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[4].delta_p", \
"pressure drop in tube [Pa]", 65, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[4].mdot", \
"mass flow rate [kg/s]", 66, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[4].delta_p_nom",\
 "pressure drop at nominal mass flow", 36, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[4].mdot_nom", \
"nominal mass flow", 37, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[4].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].fluidPortOut.p", 1,\
 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[4].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[4].mdot", 1, 5, 66, 132)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[4].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].volume.p", 1,\
 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[4].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[4].mdot", -1, 5, 66, 132)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[5].delta_p", \
"pressure drop in tube [Pa]", 67, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[2].parallelResistors.pressureLossTube[5].mdot", \
"mass flow rate [kg/s]", 68, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[5].delta_p_nom",\
 "pressure drop at nominal mass flow", 38, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[2].parallelResistors.pressureLossTube[5].mdot_nom", \
"nominal mass flow", 39, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[5].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[1].fluidPortOut.p", 1,\
 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[5].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[5].mdot", 1, 5, 68, 132)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[5].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].volume.p", 1,\
 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.pressureLossTube[5].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].parallelResistors.pressureLossTube[5].mdot", -1, 5, 68, 132)
DeclareAlias2("nLSystem[2].parallelResistors.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].volume.p", 1, 5, 52, 4)
DeclareAlias2("nLSystem[2].parallelResistors.fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].volume.fluidPortIn.m_flow", -1, 5, 53, 132)
DeclareAlias2("nLSystem[2].parallelResistors.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[1].fluidPortOut.p", 1, 5, 46, 4)
DeclareAlias2("nLSystem[2].parallelResistors.fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[1].fluidPortOut.m_flow", -1, 5, 47, 132)
DeclareVariable("nLSystem[3].numNLequations", "[:#(type=Integer)]", 20, 3, \
0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[3].withNumericJacobian", "[:#(type=Boolean)]", 21, \
false, 0.0,0.0,0.0,0,515)
DeclareParameter("nLSystem[3].volume.V", "Volume [m3]", 40, 1, 0.0,0.0,0.0,0,560)
DeclareState("nLSystem[3].volume.m", "mass of Medium in Volume [kg]", 2, 0.0, \
0.0,1.7976931348623157E+308,0.0,0,544)
DeclareDerivative("nLSystem[3].volume.der(m)", "der(mass of Medium in Volume) [kg/s]",\
 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("nLSystem[3].volume.p", "pressure of volume [Pa|bar]", 69, 0.0, \
0.0,1.7976931348623157E+308,100000.0,0,512)
DeclareParameter("nLSystem[3].volume.p_start", "initial pressure [Pa|bar]", 41, 101300,\
 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[3].volume.T", "fixed Temperature [K|degC]", 42, \
298.15, 0.0,1.7976931348623157E+308,300.0,0,560)
DeclareParameter("nLSystem[3].volume.M", "molar mass of medium (value for air)",\
 43, 0.028964, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].volume.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[3].volume.p", 1, 5, 69, 4)
DeclareVariable("nLSystem[3].volume.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 70, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("nLSystem[3].volume.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[3].volume.p", 1, 5, 69, 4)
DeclareAlias2("nLSystem[3].volume.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "parallelResistors.fluidPortIn.m_flow", -1, 5, 36, 132)
DeclareVariable("nLSystem[3].analytic_pump.delta_p", "pressure difference between inlet and outlet [Pa]",\
 71, 0.0, 0.0,0.0,100000.0,0,512)
DeclareAlias2("nLSystem[3].analytic_pump.mdot", "mass flow through pump [kg/s]",\
 "parallelResistors.fluidPortIn.m_flow", 1, 5, 36, 0)
DeclareAlias2("nLSystem[3].analytic_pump.vdot", "volume flow through pump", \
"parallelResistors.fluidPortIn.m_flow", 1, 5, 36, 0)
DeclareParameter("nLSystem[3].analytic_pump.delta_p_nom", "nominal pressure increase in pump",\
 44, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[3].analytic_pump.mdot_nom", "nominal mass flow art nominal pressure increase",\
 45, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].analytic_pump.vdot_nom", "nominal volume flow", \
"nLSystem[3].analytic_pump.mdot_nom", 1, 7, 45, 0)
DeclareParameter("nLSystem[3].analytic_pump.n_nom", "nominal rotational speed", 46,\
 10, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].analytic_pump.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[3].volume.p", 1, 5, 69, 4)
DeclareAlias2("nLSystem[3].analytic_pump.fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "parallelResistors.fluidPortIn.m_flow", 1, 5, 36, 132)
DeclareAlias2("nLSystem[3].analytic_pump.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "parallelResistors.fluidPortIn.p", 1, 5, 35, 4)
DeclareAlias2("nLSystem[3].analytic_pump.fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "parallelResistors.fluidPortIn.m_flow", -1, 5, 36, 132)
DeclareAlias2("nLSystem[3].analytic_pump.n", "rotational speed of pump", \
"nLSystem[3].realExpression1.y", 1, 5, 25, 0)
DeclareVariable("nLSystem[3].realExpression1.y", "Value of Real output", 25, 0.0,\
 0.0,0.0,0.0,0,640)
DeclareAlias2("nLSystem[3].fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "parallelResistors.fluidPortIn.p", 1, 5, 35, 4)
DeclareAlias2("nLSystem[3].fluidPortOut.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "parallelResistors.fluidPortIn.m_flow", -1, 5, 36, 132)
DeclareAlias2("nLSystem[3].fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].fluidPortOut.p", 1, 5, 57, 4)
DeclareAlias2("nLSystem[3].fluidPortIn.m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 "nLSystem[2].fluidPortOut.m_flow", -1, 5, 58, 132)
DeclareVariable("nLSystem[3].parallelResistors.nParallel", "[:#(type=Integer)]",\
 22, 3, 0.0,0.0,0.0,0,517)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[1].delta_p", \
"pressure drop in tube [Pa]", 72, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[1].mdot", \
"mass flow rate [kg/s]", 73, 0.01, 0.0,0.0,100.0,0,512)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[1].delta_p_nom",\
 "pressure drop at nominal mass flow", 47, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[1].mdot_nom", \
"nominal mass flow", 48, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[1].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].fluidPortOut.p", 1,\
 5, 57, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[1].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[1].mdot", 1, 5, 73, 132)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[1].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[3].volume.p", 1,\
 5, 69, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[1].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[1].mdot", -1, 5, 73, 132)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[2].delta_p", \
"pressure drop in tube [Pa]", 74, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[2].mdot", \
"mass flow rate [kg/s]", 75, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[2].delta_p_nom",\
 "pressure drop at nominal mass flow", 49, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[2].mdot_nom", \
"nominal mass flow", 50, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[2].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].fluidPortOut.p", 1,\
 5, 57, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[2].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[2].mdot", 1, 5, 75, 132)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[2].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[3].volume.p", 1,\
 5, 69, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[2].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[2].mdot", -1, 5, 75, 132)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[3].delta_p", \
"pressure drop in tube [Pa]", 76, 0.0, 0.0,0.0,100000.0,0,512)
DeclareVariable("nLSystem[3].parallelResistors.pressureLossTube[3].mdot", \
"mass flow rate [kg/s]", 77, 0.01, 0.0,0.0,100.0,0,576)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[3].delta_p_nom",\
 "pressure drop at nominal mass flow", 51, 200000, 0.0,0.0,0.0,0,560)
DeclareParameter("nLSystem[3].parallelResistors.pressureLossTube[3].mdot_nom", \
"nominal mass flow", 52, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[3].fluidPortIn.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[2].fluidPortOut.p", 1,\
 5, 57, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[3].fluidPortIn.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[3].mdot", 1, 5, 77, 132)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[3].fluidPortOut.p",\
 "Thermodynamic pressure in the connection point [Pa|bar]", "nLSystem[3].volume.p", 1,\
 5, 69, 4)
DeclareAlias2("nLSystem[3].parallelResistors.pressureLossTube[3].fluidPortOut.m_flow",\
 "Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].parallelResistors.pressureLossTube[3].mdot", -1, 5, 77, 132)
DeclareAlias2("nLSystem[3].parallelResistors.fluidPortOut.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[3].volume.p", 1, 5, 69, 4)
DeclareAlias2("nLSystem[3].parallelResistors.fluidPortOut.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[3].volume.fluidPortIn.m_flow", -1, 5, 70, 132)
DeclareAlias2("nLSystem[3].parallelResistors.fluidPortIn.p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "nLSystem[2].fluidPortOut.p", 1, 5, 57, 4)
DeclareAlias2("nLSystem[3].parallelResistors.fluidPortIn.m_flow", \
"Mass flow rate from the connection point into the component [kg/s]", \
"nLSystem[2].fluidPortOut.m_flow", -1, 5, 58, 132)
DeclareOutput("CPUtime", "[s]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("EventCounter", "", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[1].Calls", "Number of calls to solve this system",\
 78, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[1].Residues", "Number of evaluations of the system residual",\
 79, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[1].Iterations", "Number of iterations performed to solve this system",\
 80, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[1].Jacobians", "Number of evaluations of the analytic system Jacobian",\
 81, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[2].Calls", "Number of calls to solve this system",\
 82, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[2].Residues", "Number of evaluations of the system residual",\
 83, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[2].Iterations", "Number of iterations performed to solve this system",\
 84, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[2].Jacobians", "Number of evaluations of the analytic system Jacobian",\
 85, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[3].Calls", "Number of calls to solve this system",\
 86, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[3].Residues", "Number of evaluations of the system residual",\
 87, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[3].Iterations", "Number of iterations performed to solve this system",\
 88, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[3].Jacobians", "Number of evaluations of the analytic system Jacobian",\
 89, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[4].Calls", "Number of calls to solve this system",\
 90, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[4].Residues", "Number of evaluations of the system residual",\
 91, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[4].Iterations", "Number of iterations performed to solve this system",\
 92, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("NonlinearSystems.simulation[4].Jacobians", "Number of evaluations of the analytic system Jacobian",\
 93, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,44), 0.0, 6);
DoRemember_(DYNX(W_,49), 0.01, 12);
DoRemember_(DYNX(W_,51), 0.01, 11);
DoRemember_(DYNX(W_,41), DYNX(DP_,13), 0);
DoRemember_(DYNX(W_,55), 0.0, 10);
DoRemember_(DYNX(W_,62), 0.01, 5);
DoRemember_(DYNX(W_,64), 0.01, 4);
DoRemember_(DYNX(W_,66), 0.01, 3);
DoRemember_(DYNX(W_,68), 0.01, 2);
DoRemember_(DYNX(W_,52), DYNX(DP_,24), 1);
DoRemember_(DYNX(W_,75), 0.01, 9);
DoRemember_(DYNX(W_,77), 0.01, 8);
DoRemember_(DYNX(W_,69), DYNX(DP_,41), 7);
DoRemember_(DYNX(W_,27), 0.01, 16);
DoRemember_(DYNX(W_,29), 0.01, 15);
DoRemember_(DYNX(W_,31), 0.01, 14);
DoRemember_(DYNX(W_,33), 0.01, 13);
EndEqBlock
EndDataBlock
